version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  target-branch: "flammables"
  open-pull-requests-limit: 10
  assignees:
      - "flamableassassin"
